version: '3.8'

services:
  tracker:
    image: tracker
    container_name: tracker
    environment:
      - TRACKER_HOST=tracker:50051
    ports:
      - "50051:50051"

  peer1:
    image: peer
    container_name: peer1
    environment:
      - TRACKER_ADDR=tracker:50051
      - PEER_HOST=peer1:50052
    ports:
      - "50052:50052"
    depends_on:
      - tracker 
  peer2:
    image: peer
    container_name: peer2
    environment:
      - TRACKER_ADDR=tracker:50051
      - PEER_HOST=peer2:50053
    ports:
      - "50053:50053"
    depends_on:
      - tracker 

